### ISSUE TITLE
Broken on nightly due to type change

### ISSUE THREAD

**Issue by oxinabox** [JuliaDiff/Diffractor.jl#124]
From the tests
```julia
julia> using TestEnv; TestEnv.activate(); using Symbolics, Diffractor

julia> @variables ω α β γ δ ϵ ζ η
       (x1, c1) = ∂⃖{3}()(exp, ω)
ERROR: TypeError: in opaque_closure_method, expected Int64, got a value of type Int32

Some of the types have been truncated in the stacktrace for improved reading. To emit complete information
in the stack trace, evaluate `TruncatedStacktraces.VERBOSE[] = true` and re-run the code.

Stacktrace:
 [1] ∂⃖
   @ ~/JuliaEnvs/Diffractor.jl/src/stage1/generated.jl:223 [inlined]
 [2] (::∂⃖{3})(f::typeof(exp), args::Num)
   @ Diffractor ~/JuliaEnvs/Diffractor.jl/src/stage1/generated.jl:66
 [3] top-level scope
   @ REPL[38]:2
```

Nightly first failed with this on
**22 Feb** https://github.com/JuliaDiff/Diffractor.jl/actions/runs/4229848232
and last worked on
**21 Feb** https://github.com/JuliaDiff/Diffractor.jl/actions/runs/4229848232

So there is a narrow window in what change could have caused this failure

**Comment by oscardssmith** [comment]
Is this the same as https://github.com/JuliaDiff/Diffractor.jl/issues/122 or a separate breakage?

**Comment by oxinabox** [comment]
Pretty sure it is seperate, its a different error message

**Comment by oxinabox** [comment]
Pretty sure the cause was https://github.com/JuliaLang/julia/pull/48739

so somewhere with `nargs` being passed in

**Comment by oxinabox** [comment]
Simpler test case:
```
julia> using Diffractor

julia> var"'" = Diffractor.PrimeDerivativeBack
Diffractor.PrimeDerivativeBack

julia> sin'''(1.0)
```

Needs at least 3rd derivative.
Interestingly once i put my current fix in 3rd works, but 4th segfaults...
