### ISSUE TITLE
Broken on julia nightly

### ISSUE THREAD

**Issue by oxinabox** [JuliaDiff/Diffractor.jl#196]
It broke last night. but it was working yesterday afternoon.
So it wasn't something we changed.
Further I can narrow it to some change that landed yesterday afternoon, as I built julia in the morning
It works on 
```
Julia Version 1.11.0-DEV.169
Commit 912423456d (2023-07-25 15:59 UTC)
``` 
so we need to look at commits after that

error is:
```
JIT session error: Symbols not found: [ jl_global#11 ]
JIT session error: Symbols not found: [ jl_global#11 ]
JIT session error: Symbols not found: [ jl_global#37 ]
JIT session error: Symbols not found: [ jl_global#39 ]
JIT session error: Symbols not found: [ jl_global#38 ]
JIT session error: Symbols not found: [ jl_global#2 ]
JIT session error: Symbols not found: [ +ChainRulesCore.AbstractZero#58, jl_global#22, jl_global#60, jl_global#61 ]
```
See [CI logs](https://github.com/JuliaDiff/Diffractor.jl/actions/runs/5665337522/job/15350005843#step:6:332)

**Comment by aviatesk** [comment]
Let's close this. The failures on nightly are different now.
