### ISSUE TITLE
Error when taking Hessian

### ISSUE THREAD

**Issue by cafaxo** [JuliaDiff/Diffractor.jl#201]
When trying to compute a Hessian via AbstractDifferentiation, I get

```julia
julia> AbstractDifferentiation.hessian(DiffractorForwardBackend(), prod, ones(3))
ERROR: MethodError: no method matching setindex!(::ChainRulesCore.ZeroTangent, ::Float64, ::Int64)
```

Error looks similar to https://github.com/JuliaDiff/Diffractor.jl/issues/200

**Comment by oxinabox** [comment]
Yes, I believe this is #200 so will be closed once that is fixed.
So closing as duplicate for now.
