### ISSUE TITLE
Cannot compute the second derivative of a generic function via forward mode AD

### ISSUE THREAD

**Issue by YingboMa** [JuliaDiff/Diffractor.jl#21]
MWE:
```julia
julia> foo(x) = cos(x) * sin(x)
foo (generic function with 1 method)

julia> const var"'" = Diffractor.PrimeDerivativeFwd
Diffractor.PrimeDerivativeFwd

julia> @time foo''(1.0)
ERROR: MethodError: no method matching apply_type(::Type{Base.Broadcast.Broadcasted}, ::Type{Base.Broadcast.DefaultArrayStyle{0}}, ::Type{Nothing}, ::Type{typeof(*)}, ::Type{Tuple{Float64, Float64}})
Stacktrace:
  [1] ∂☆nomethd(args::Any)
    @ Diffractor ~/src/julia/Diffractor/src/stage1/recurse_fwd.jl:115
  [2] macro expansion
    @ ~/src/julia/Diffractor/src/stage1/recurse_fwd.jl:0 [inlined]
  [3] (::Diffractor.∂☆recurse{1})(::Diffractor.UniformBu, ::Diffractor.UniformBu, ::Diffractor.UniformBu, ::Diffractor.UniformBu, ::Diffractor.UniformBu, ::Diffractor.UniformBu)
    @ Diffractor ~/src/julia/Diffractor/src/stage1/recurse_fwd.jl:160
```

**Comment by Keno** [comment]
This is a too narrow rule in ChainRules. This is fixed in https://github.com/JuliaDiff/ChainRules.jl/pull/463/, but I've lost track of what needs to happen there to get that merged. I guess @simeonschaub has been working on pushing it through. The Manifest that's in the Diffractor repo should work in the meantime.

**Comment by YingboMa** [comment]
I cannot use the Manifest because there's https://github.com/JuliaDiff/Diffractor.jl/blob/7e8c45a9d088874cfffe3ae62d9c7be167ab8761/Manifest.toml#L21 :-)

**Comment by Keno** [comment]
Whoops, I meant to point that at PR branch. Must have accidentally committed it back.

**Comment by YingboMa** [comment]
Also, Pkg complains that
```julia
ERROR: Did not find tree_hash 17488e29b9dd0aded59a7dd22f444edd96d32dc5 for `ChainRulesCore [d360d2e6]`
```
https://github.com/JuliaDiff/Diffractor.jl/blob/7e8c45a9d088874cfffe3ae62d9c7be167ab8761/Manifest.toml#L25-L31

**Comment by Keno** [comment]
Fixed with the ChainRules bump
