### ISSUE TITLE
Eras mode: Taylor or it Eras

### ISSUE THREAD

**Issue by oxinabox** [JuliaDiff/Diffractor.jl#252]
Right now if a particular derivative can not be represented as a TaylorBundle we fall back and represent it as a ExplictTangentBundle.

For the last 6 months we have been trying the other option: if it can't be represented as a TaylorBundle erroring out in various branches that include `for_cedar` in the name.

This is kinda annoying since it will error sometimes -- but you can generally fix that (if you are running your own optimization passes) by optimizing until all the diffractor code vanishes, before doing the next level of nested AD.
But it has the key advantage of being much faster since it avoids the type instability between TaylorTangent vs ExplictTangents

Anyway this maintainign this feature in a seperate branch is really annoying.
So we should add a "Eras mode" type parameter to ` ∂☆` to tell if if we should error or use ExplictTangents.

To be safe in Eras mode,  
it is sufficient, but not necessary, to be doing nested AD with respect to the same variable -- this naturally transforms into a Taylor AD.
It also works in other cases where (likely by problem construction) ADing with respect to a second variable happens to result in something that can be represented with a TaylorBundle also. (You need your different partials to happen to be exactly equal).

**Comment by ChrisRackauckas** [comment]
Love it.
