### ISSUE TITLE
Strange behaviour of the derivative

### ISSUE THREAD

**Issue by Arkoniak** [JuliaDiff/Diffractor.jl#26]
I do not know, maybe I am missing something simple here

```julia
using Diffractor
using Plots

function f1(x)
    res = 0.0
    for i in 1:10
        res += x^i
    end
    res
end

f(x) = let var"'" = Diffractor.PrimeDerivativeFwd 
    f1'(x)
end


xs = -0.5:0.01:0.5
plot(xs, f1.(xs), legend = nothing)
plot!(xs, f.(xs))
```

It has this weird glitch in zero.

![flameshot-2021-07-30T12-23-07](https://user-images.githubusercontent.com/2630519/127632059-335bd016-c5ba-48b1-8411-3743ba13dcdd.png)

Info:
```julia
julia> versioninfo()
Julia Version 1.8.0-DEV.74
Commit ba5fffca7b (2021-06-24 02:52 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.0 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4
  JULIA_PKG_SERVER =

(Diffractor) pkg> st
      Status `~/Projects/BabySteps/Diffractor/Project.toml`
  [d360d2e6] ChainRulesCore v1.0.2
  [9f5e2b26] Diffractor v0.1.1 `~/.julia/dev/Diffractor`
  [91a5bcdd] Plots v1.19.4
```

**Comment by antoine-levitt** [comment]
Simpler probably related issue:
```
julia> Diffractor.PrimeDerivativeFwd(x -> x^1)(0.0)
NaN
```

**Comment by mcabbott** [comment]
Looks like it might be the same as https://github.com/FluxML/Zygote.jl/issues/1036, Antoine's example on Zygote:
```
julia> using Zygote

julia> gradient(x -> x^1, 0.0)
(1.0,)

julia> gradient(x -> x^1.0, 0.0)
(0.0,)
```

**Comment by antoine-levitt** [comment]
Looks unrelated: this current bug is fixed by https://github.com/JuliaDiff/ChainRules.jl/pull/485. The linked issue is about fractional powers, which is much more tricky to get right (because it is singular in general for float powers, although happens to be well-defined at integers)

**Comment by mcabbott** [comment]
I got some strange answers from reverse mode for this function, BTW. Only with Julia 1.8, details here: https://github.com/JuliaDiff/ChainRules.jl/pull/513#discussion_r702206095
