### ISSUE TITLE
Is there a Diffractor-native interface?

### ISSUE THREAD

**Issue by gdalle** [JuliaDiff/Diffractor.jl#287]
For operators like `gradient` and `jacobian` in DifferentiationInterface.jl, I'm wondering if the best thing to do is just call the relevant AbstractDifferentiation functions? From what I can read in https://github.com/JuliaDiff/Diffractor.jl/blob/main/src/AbstractDifferentiation.jl, it all comes down to the pushforward anyway.

Related: 
- https://github.com/gdalle/DifferentiationInterface.jl/issues/115

**Comment by oxinabox** [comment]
I would say this is the diffractor naitive interface.
https://github.com/JuliaDiff/Diffractor.jl/blob/a444b7f707b5c97e771c0afe23190dd8b137fc75/src/AbstractDifferentiation.jl#L17-L18

Its what I normally work with.
It's not documented as such but it does just come down to that pushforward.

**Comment by gdalle** [comment]
Fair enough!
The idea is that when we compare autodiff backends in DifferentiationInterface, we want to have the optimal performance for each.
In Diffractor's case, every one of our operators can be implemented using
https://github.com/gdalle/DifferentiationInterface.jl/blob/07d272af4351bc44344c9ba90705df6c4454a9f8/ext/DifferentiationInterfaceDiffractorExt/DifferentiationInterfaceDiffractorExt.jl#L12-L16
so if there are no faster shortcuts in specific cases, let's keep it that way!
