### ISSUE TITLE
No method matching adjoint(::typeof(f))

### ISSUE THREAD

**Issue by NiklasGustafsson** [JuliaDiff/Diffractor.jl#74]
The first thing I try with Diffractor blows up. 

Is there something I'm missing about how to use it? 

```
julia> using Diffractor

julia> f(x) = 4*x + 5
f (generic function with 1 method)

julia> f(10)
45

julia> f'(10)
ERROR: MethodError: no method matching adjoint(::typeof(f))
Closest candidates are:
  adjoint(::Union{LinearAlgebra.QR, LinearAlgebra.QRCompactWY, LinearAlgebra.QRPivoted}) at C:\dd\Julia 1.7.2\share\julia\stdlib\v1.7\LinearAlgebra\src\qr.jl:509
  adjoint(::Union{LinearAlgebra.Cholesky, LinearAlgebra.CholeskyPivoted}) at C:\dd\Julia 1.7.2\share\julia\stdlib\v1.7\LinearAlgebra\src\cholesky.jl:538
  adjoint(::ChainRulesCore.AbstractZero) at C:\Users\niklasg\.julia\packages\ChainRulesCore\IzITE\src\tangent_types\abstract_zero.jl:23
  ...
Stacktrace:
 [1] top-level scope
   @ REPL[4]:1
```

It works fine with Zygote:
```
julia> using Zygote

julia> f(x) = 4*x + 5
f (generic function with 1 method)

julia> f(10)
45

julia> f'(10)
4.0
```

**Comment by NiklasGustafsson** [comment]
@Keno -- thanks for that tip. It's curious that Zygote gets away with it.

**Comment by Keno** [comment]
Zygote just overloads `Base.adjoint` (i.e. array conjugate transpose), which is the default use of that syntax, but I didn't want to do that for Diffractor, because you can have things for which both adjoint and AD make sense and the two meanings step on each other.

**Comment by Keno** [comment]
I think somebody added a mechanism to base to add error hints for these kind of situations - let me see if I can do that.
